In [38]:
import pandas as pd
import numpy as np
import boto3
from sklearn.model_selection import train_test_split
import sagemaker
from sagemaker import Session
import io
import sagemaker.amazon.common as smac
import os
from sagemaker.amazon.amazon_estimator import get_image_uri
from sagemaker.serializers import CSVSerializer
from sagemaker.deserializers import JSONDeserializer

In [7]:
df = pd.read_csv("student_scores.csv")
df.head()

   Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [8]:
df.shape

(25, 2)

In [9]:
x=df[["Hours"]]
y=df[["Scores"]]

In [10]:
x.dtypes
x=x.astype("float32")
y=y.astype("float32")

In [11]:
y.dtypes

Scores    float32
dtype: object

In [12]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [13]:
X_train = X_train.reset_index(drop=True)
X_test  = X_test.reset_index(drop=True)
y_train = y_train.reset_index(drop=True)
y_test  = y_test.reset_index(drop=True)

In [14]:
X_train

    Hours
0     7.4
1     2.7
2     6.9
3     4.5
4     1.5
5     3.2
6     4.8
7     3.5
8     2.5
9     8.5
10    5.5
11    9.2
12    8.3
13    7.8
14    5.9
15    2.5
16    6.1
17    1.9
18    1.1
19    2.7

In [15]:
y_train=y_train.iloc[:,0]

In [16]:
y_train

0     69.0
1     30.0
2     76.0
3     41.0
4     20.0
5     27.0
6     54.0
7     30.0
8     30.0
9     75.0
10    60.0
11    88.0
12    81.0
13    86.0
14    62.0
15    21.0
16    67.0
17    24.0
18    17.0
19    25.0
Name: Scores, dtype: float32

In [17]:
y_test=y_test.iloc[:,0]

In [18]:
sagemaker_session=sagemaker.Session()
bucket_name="vignesh-sagemaker-test"
prefix="linear-learner"
role=sagemaker.get_execution_role()

In [19]:
X_train = X_train.to_numpy()
y_train = y_train.to_numpy()

In [20]:
buf=io.BytesIO()
smac.write_numpy_to_dense_tensor(buf,X_train,y_train)
buf.seek(0)

0

In [21]:
key="student-data"
boto3.resource('s3').Bucket(bucket_name).Object(os.path.join(prefix,'train',key)).upload_fileobj(buf)
s3_train_data=f"s3://{bucket_name}/{prefix}/train/{key}"
print("Data Uploaded",s3_train_data)

Data Uploaded s3://vignesh-sagemaker-test/linear-learner/train/student-data

In [22]:
X_test=np.array(X_test)
buf=io.BytesIO()
smac.write_numpy_to_dense_tensor(buf,X_test,y_test)
buf.seek(0)
key="student-data-test"
boto3.resource('s3').Bucket(bucket_name).Object(os.path.join(prefix,'test',key)).upload_fileobj(buf)
s3_test_data=f"s3://{bucket_name}/{prefix}/test/{key}"
print("Data Uploaded",s3_test_data)

Data Uploaded s3://vignesh-sagemaker-test/linear-learner/test/student-data-test

In [25]:
output_location=f"s3://{bucket_name}/{prefix}/output"
output_location

's3://vignesh-sagemaker-test/linear-learner/output'

In [29]:
container = sagemaker.image_uris.retrieve(
    "linear-learner",
    boto3.Session().region_name
)
print(container)

382416733822.dkr.ecr.us-east-1.amazonaws.com/linear-learner:1

In [33]:
linear = sagemaker.estimator.Estimator(
    image_uri=container,
    role=role,
    instance_count=1,
    instance_type="ml.c4.4xlarge",
    output_path=output_location,
    sagemaker_session=sagemaker_session
)

In [34]:
linear.set_hyperparameters(
    feature_dim=1,
    predictor_type="regressor",
    mini_batch_size=4,
    epochs=6,
    num_models=32,
    loss="absolute_loss"
)

In [35]:
linear.fit({"train": s3_train_data})

INFO:sagemaker.telemetry.telemetry_logging:SageMaker Python SDK will collect telemetry to help us better understand our user's needs, diagnose issues, and deliver additional features.
To opt out of telemetry, please disable via TelemetryOptOut parameter in SDK defaults config. For more information, refer to https://sagemaker.readthedocs.io/en/stable/overview.html#configuring-and-using-defaults-with-the-sagemaker-python-sdk.
INFO:sagemaker:Creating training-job with name: linear-learner-2026-03-15-11-34-09-211

2026-03-15 11:34:10 Starting - Starting the training job...
2026-03-15 11:34:25 Starting - Preparing the instances for training...
2026-03-15 11:35:04 Downloading - Downloading the training image......
2026-03-15 11:36:05 Training - Training image download completed. Training in progress....
2026-03-15 11:36:35 Uploading - Uploading generated training modelDocker entrypoint called with argument(s): train
Running default environment configuration script
[03/15/2026 11:36:28 INFO 139913908160320] Reading default configuration from /opt/amazon/lib/python3.8/site-packages/algorithm/resources/default-input.json: {'mini_batch_size': '1000', 'epochs': '15', 'feature_dim': 'auto', 'use_bias': 'true', 'binary_classifier_model_selection_criteria': 'accuracy', 'f_beta': '1.0', 'target_recall': '0.8', 'target_precision': '0.8', 'num_models': 'auto', 'num_calibration_samples': '10000000', 'init_method': 'uniform', 'init_scale': '0.07', 'init_sigma': '0.01', 'init_bias': '0.0', 'optimizer': 'auto', 'loss': 'auto', 'margin': '1.0', 'quantile': '0.5', 'loss_insensitivity': '0.01', 'huber_delta': '1.0', 'num_classes': '1', 'accuracy_top_k': '3', 'wd': 'auto', 'l1': 'auto', 'momentum': 'auto', 'learning_rate': 'auto', 'beta_1': 'auto', 'beta_2': 'auto', 'bias_lr_mult': 'auto', 'bias_wd_mult': 'auto', 'use_lr_scheduler': 'true', 'lr_scheduler_step': 'auto', 'lr_scheduler_factor': 'auto', 'lr_scheduler_minimum_lr': 'auto', 'positive_example_weight_mult': '1.0', 'balance_multiclass_weights': 'false', 'normalize_data': 'true', 'normalize_label': 'auto', 'unbias_data': 'auto', 'unbias_label': 'auto', 'num_point_for_scaler': '10000', '_kvstore': 'auto', '_num_gpus': 'auto', '_num_kv_servers': 'auto', '_log_level': 'info', '_tuning_objective_metric': '', 'early_stopping_patience': '3', 'early_stopping_tolerance': '0.001', '_enable_profiler': 'false'}
[03/15/2026 11:36:28 INFO 139913908160320] Merging with provided configuration from /opt/ml/input/config/hyperparameters.json: {'epochs': '6', 'feature_dim': '1', 'loss': 'absolute_loss', 'mini_batch_size': '4', 'num_models': '32', 'predictor_type': 'regressor'}
[03/15/2026 11:36:28 INFO 139913908160320] Final configuration: {'mini_batch_size': '4', 'epochs': '6', 'feature_dim': '1', 'use_bias': 'true', 'binary_classifier_model_selection_criteria': 'accuracy', 'f_beta': '1.0', 'target_recall': '0.8', 'target_precision': '0.8', 'num_models': '32', 'num_calibration_samples': '10000000', 'init_method': 'uniform', 'init_scale': '0.07', 'init_sigma': '0.01', 'init_bias': '0.0', 'optimizer': 'auto', 'loss': 'absolute_loss', 'margin': '1.0', 'quantile': '0.5', 'loss_insensitivity': '0.01', 'huber_delta': '1.0', 'num_classes': '1', 'accuracy_top_k': '3', 'wd': 'auto', 'l1': 'auto', 'momentum': 'auto', 'learning_rate': 'auto', 'beta_1': 'auto', 'beta_2': 'auto', 'bias_lr_mult': 'auto', 'bias_wd_mult': 'auto', 'use_lr_scheduler': 'true', 'lr_scheduler_step': 'auto', 'lr_scheduler_factor': 'auto', 'lr_scheduler_minimum_lr': 'auto', 'positive_example_weight_mult': '1.0', 'balance_multiclass_weights': 'false', 'normalize_data': 'true', 'normalize_label': 'auto', 'unbias_data': 'auto', 'unbias_label': 'auto', 'num_point_for_scaler': '10000', '_kvstore': 'auto', '_num_gpus': 'auto', '_num_kv_servers': 'auto', '_log_level': 'info', '_tuning_objective_metric': '', 'early_stopping_patience': '3', 'early_stopping_tolerance': '0.001', '_enable_profiler': 'false', 'predictor_type': 'regressor'}
/opt/amazon/lib/python3.8/site-packages/mxnet/model.py:97: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if num_device is 1 and 'dist' not in kvstore:
/opt/amazon/lib/python3.8/site-packages/scipy/optimize/_shgo.py:495: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if cons['type'] is 'ineq':
/opt/amazon/lib/python3.8/site-packages/scipy/optimize/_shgo.py:743: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(self.X_min) is not 0:
[03/15/2026 11:36:30 WARNING 139913908160320] Loggers have already been setup.
[03/15/2026 11:36:30 INFO 139913908160320] Final configuration: {'mini_batch_size': '4', 'epochs': '6', 'feature_dim': '1', 'use_bias': 'true', 'binary_classifier_model_selection_criteria': 'accuracy', 'f_beta': '1.0', 'target_recall': '0.8', 'target_precision': '0.8', 'num_models': '32', 'num_calibration_samples': '10000000', 'init_method': 'uniform', 'init_scale': '0.07', 'init_sigma': '0.01', 'init_bias': '0.0', 'optimizer': 'auto', 'loss': 'absolute_loss', 'margin': '1.0', 'quantile': '0.5', 'loss_insensitivity': '0.01', 'huber_delta': '1.0', 'num_classes': '1', 'accuracy_top_k': '3', 'wd': 'auto', 'l1': 'auto', 'momentum': 'auto', 'learning_rate': 'auto', 'beta_1': 'auto', 'beta_2': 'auto', 'bias_lr_mult': 'auto', 'bias_wd_mult': 'auto', 'use_lr_scheduler': 'true', 'lr_scheduler_step': 'auto', 'lr_scheduler_factor': 'auto', 'lr_scheduler_minimum_lr': 'auto', 'positive_example_weight_mult': '1.0', 'balance_multiclass_weights': 'false', 'normalize_data': 'true', 'normalize_label': 'auto', 'unbias_data': 'auto', 'unbias_label': 'auto', 'num_point_for_scaler': '10000', '_kvstore': 'auto', '_num_gpus': 'auto', '_num_kv_servers': 'auto', '_log_level': 'info', '_tuning_objective_metric': '', 'early_stopping_patience': '3', 'early_stopping_tolerance': '0.001', '_enable_profiler': 'false', 'predictor_type': 'regressor'}
[03/15/2026 11:36:30 WARNING 139913908160320] Loggers have already been setup.
Process 7 is a worker.
[03/15/2026 11:36:30 INFO 139913908160320] Using default worker.
[03/15/2026 11:36:30 INFO 139913908160320] Checkpoint loading and saving are disabled.
[2026-03-15 11:36:30.447] [tensorio] [info] epoch_stats={"data_pipeline": "/opt/ml/input/data/train", "epoch": 0, "duration": 9, "num_examples": 1, "num_bytes": 192}
[03/15/2026 11:36:30 INFO 139913908160320] Create Store: local
[2026-03-15 11:36:30.474] [tensorio] [info] epoch_stats={"data_pipeline": "/opt/ml/input/data/train", "epoch": 1, "duration": 26, "num_examples": 5, "num_bytes": 960}
[03/15/2026 11:36:30 INFO 139913908160320] Scaler algorithm parameters
 <algorithm.scaler.ScalerAlgorithmStable object at 0x7f3f6b5c8490>
[03/15/2026 11:36:30 INFO 139913908160320] Scaling model computed with parameters:
 {'stdev_label':
[24.329561]
<NDArray 1 @cpu(0)>, 'stdev_weight':
[2.5057683]
<NDArray 1 @cpu(0)>, 'mean_label':
[49.15]
<NDArray 1 @cpu(0)>, 'mean_weight':
[4.8250003]
<NDArray 1 @cpu(0)>}
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[03/15/2026 11:36:30 INFO 139913908160320] nvidia-smi: took 0.032 seconds to run.
[03/15/2026 11:36:30 INFO 139913908160320] nvidia-smi identified 0 GPUs.
[03/15/2026 11:36:30 INFO 139913908160320] Number of GPUs being used: 0
#metrics {"StartTime": 1773574590.557472, "EndTime": 1773574590.5575018, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "Meta": "init_train_data_iter"}, "Metrics": {"Total Records Seen": {"sum": 24.0, "count": 1, "min": 24, "max": 24}, "Total Batches Seen": {"sum": 6.0, "count": 1, "min": 6, "max": 6}, "Max Records Seen Between Resets": {"sum": 20.0, "count": 1, "min": 20, "max": 20}, "Max Batches Seen Between Resets": {"sum": 5.0, "count": 1, "min": 5, "max": 5}, "Reset Count": {"sum": 2.0, "count": 1, "min": 2, "max": 2}, "Number of Records Since Last Reset": {"sum": 0.0, "count": 1, "min": 0, "max": 0}, "Number of Batches Since Last Reset": {"sum": 0.0, "count": 1, "min": 0, "max": 0}}}
[2026-03-15 11:36:30.614] [tensorio] [info] epoch_stats={"data_pipeline": "/opt/ml/input/data/train", "epoch": 4, "duration": 57, "num_examples": 5, "num_bytes": 960}
#metrics {"StartTime": 1773574590.6150134, "EndTime": 1773574590.6150544, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 0}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9207397699356079, "count": 1, "min": 0.9207397699356079, "max": 0.9207397699356079}}}
#metrics {"StartTime": 1773574590.6151044, "EndTime": 1773574590.6151125, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 1}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9410889267921447, "count": 1, "min": 0.9410889267921447, "max": 0.9410889267921447}}}
#metrics {"StartTime": 1773574590.615137, "EndTime": 1773574590.6151443, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 2}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9232047915458679, "count": 1, "min": 0.9232047915458679, "max": 0.9232047915458679}}}
#metrics {"StartTime": 1773574590.615175, "EndTime": 1773574590.6151805, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 3}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9400490045547485, "count": 1, "min": 0.9400490045547485, "max": 0.9400490045547485}}}
#metrics {"StartTime": 1773574590.615201, "EndTime": 1773574590.6152062, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 4}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.8245398044586182, "count": 1, "min": 0.8245398044586182, "max": 0.8245398044586182}}}
#metrics {"StartTime": 1773574590.615226, "EndTime": 1773574590.6152308, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 5}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.8344552040100097, "count": 1, "min": 0.8344552040100097, "max": 0.8344552040100097}}}
#metrics {"StartTime": 1773574590.6152503, "EndTime": 1773574590.615255, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 6}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9191947102546691, "count": 1, "min": 0.9191947102546691, "max": 0.9191947102546691}}}
#metrics {"StartTime": 1773574590.6152837, "EndTime": 1773574590.6152894, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 7}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.8896914839744567, "count": 1, "min": 0.8896914839744567, "max": 0.8896914839744567}}}
#metrics {"StartTime": 1773574590.6153164, "EndTime": 1773574590.6153228, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 8}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9778751492500305, "count": 1, "min": 0.9778751492500305, "max": 0.9778751492500305}}}
#metrics {"StartTime": 1773574590.6153529, "EndTime": 1773574590.6153603, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 9}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9084437727928162, "count": 1, "min": 0.9084437727928162, "max": 0.9084437727928162}}}
#metrics {"StartTime": 1773574590.615391, "EndTime": 1773574590.6153986, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 10}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9152907371520996, "count": 1, "min": 0.9152907371520996, "max": 0.9152907371520996}}}
#metrics {"StartTime": 1773574590.6154292, "EndTime": 1773574590.6154366, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 11}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9001500964164734, "count": 1, "min": 0.9001500964164734, "max": 0.9001500964164734}}}
#metrics {"StartTime": 1773574590.6154692, "EndTime": 1773574590.6154764, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 12}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.8335612416267395, "count": 1, "min": 0.8335612416267395, "max": 0.8335612416267395}}}
#metrics {"StartTime": 1773574590.615507, "EndTime": 1773574590.6155138, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 13}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.8603106260299682, "count": 1, "min": 0.8603106260299682, "max": 0.8603106260299682}}}
#metrics {"StartTime": 1773574590.6155446, "EndTime": 1773574590.615552, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 14}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.8320460557937622, "count": 1, "min": 0.8320460557937622, "max": 0.8320460557937622}}}
#metrics {"StartTime": 1773574590.6155822, "EndTime": 1773574590.6155891, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 15}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.8667215585708619, "count": 1, "min": 0.8667215585708619, "max": 0.8667215585708619}}}
#metrics {"StartTime": 1773574590.6156194, "EndTime": 1773574590.6156268, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 16}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.8838173270225524, "count": 1, "min": 0.8838173270225524, "max": 0.8838173270225524}}}
#metrics {"StartTime": 1773574590.6156569, "EndTime": 1773574590.6156642, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 17}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9362277984619141, "count": 1, "min": 0.9362277984619141, "max": 0.9362277984619141}}}
#metrics {"StartTime": 1773574590.6156948, "EndTime": 1773574590.6157017, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 18}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9114932894706727, "count": 1, "min": 0.9114932894706727, "max": 0.9114932894706727}}}
#metrics {"StartTime": 1773574590.6162703, "EndTime": 1773574590.6162796, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 19}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.908730399608612, "count": 1, "min": 0.908730399608612, "max": 0.908730399608612}}}
#metrics {"StartTime": 1773574590.6163125, "EndTime": 1773574590.61632, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 20}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.8807818174362183, "count": 1, "min": 0.8807818174362183, "max": 0.8807818174362183}}}
#metrics {"StartTime": 1773574590.6163507, "EndTime": 1773574590.6163585, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 21}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.8961592316627502, "count": 1, "min": 0.8961592316627502, "max": 0.8961592316627502}}}
#metrics {"StartTime": 1773574590.6163895, "EndTime": 1773574590.6163971, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 22}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.8310075640678406, "count": 1, "min": 0.8310075640678406, "max": 0.8310075640678406}}}
#metrics {"StartTime": 1773574590.6164267, "EndTime": 1773574590.616434, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 23}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9226258873939515, "count": 1, "min": 0.9226258873939515, "max": 0.9226258873939515}}}
#metrics {"StartTime": 1773574590.6164658, "EndTime": 1773574590.6164737, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 24}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.8888573408126831, "count": 1, "min": 0.8888573408126831, "max": 0.8888573408126831}}}
#metrics {"StartTime": 1773574590.6165204, "EndTime": 1773574590.616528, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 25}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9549278020858765, "count": 1, "min": 0.9549278020858765, "max": 0.9549278020858765}}}
#metrics {"StartTime": 1773574590.6165593, "EndTime": 1773574590.6165671, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 26}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9413031578063965, "count": 1, "min": 0.9413031578063965, "max": 0.9413031578063965}}}
#metrics {"StartTime": 1773574590.6165977, "EndTime": 1773574590.6166053, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 27}, "Metrics": {"train_absolute_loss_objective": {"sum": 0.9303088545799255, "count": 1, "min": 0.9303088545799255, "max": 0.9303088545799255}}}
#metrics {"StartTime": 1773574590.6166356, "EndTime": 1773574590.6166432, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 28}, "Metrics": {"train_absolute_loss_objective": {"sum": 1.031805968284607, "count": 1, "min": 1.031805968284607, "max": 1.031805968284607}}}
#metrics {"StartTime": 1773574590.6166728, "EndTime": 1773574590.6166801, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 29}, "Metrics": {"train_absolute_loss_objective": {"sum": 1.032899594306946, "count": 1, "min": 1.032899594306946, "max": 1.032899594306946}}}
#metrics {"StartTime": 1773574590.6167102, "EndTime": 1773574590.6167176, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 30}, "Metrics": {"train_absolute_loss_objective": {"sum": 1.0413731813430787, "count": 1, "min": 1.0413731813430787, "max": 1.0413731813430787}}}
#metrics {"StartTime": 1773574590.6167467, "EndTime": 1773574590.6167543, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 31}, "Metrics": {"train_absolute_loss_objective": {"sum": 1.028122854232788, "count": 1, "min": 1.028122854232788, "max": 1.028122854232788}}}
[03/15/2026 11:36:30 INFO 139913908160320] #quality_metric: host=algo-1, epoch=0, train absolute_loss_objective <loss>=0.9207397699356079
[03/15/2026 11:36:30 INFO 139913908160320] #early_stopping_criteria_metric: host=algo-1, epoch=0, criteria=absolute_loss_objective, value=0.8245398044586182
[03/15/2026 11:36:30 INFO 139913908160320] Epoch 0: Loss improved. Updating best model
[03/15/2026 11:36:30 INFO 139913908160320] Saving model for epoch: 0
[03/15/2026 11:36:30 INFO 139913908160320] Saved checkpoint to "/tmp/tmpn65tu7yj/mx-mod-0000.params"
[03/15/2026 11:36:30 INFO 139913908160320] #progress_metric: host=algo-1, completed 16.666666666666668 % of epochs
#metrics {"StartTime": 1773574590.5576851, "EndTime": 1773574590.623044, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "Meta": "training_data_iter"}, "Metrics": {"Total Records Seen": {"sum": 44.0, "count": 1, "min": 44, "max": 44}, "Total Batches Seen": {"sum": 11.0, "count": 1, "min": 11, "max": 11}, "Max Records Seen Between Resets": {"sum": 20.0, "count": 1, "min": 20, "max": 20}, "Max Batches Seen Between Resets": {"sum": 5.0, "count": 1, "min": 5, "max": 5}, "Reset Count": {"sum": 3.0, "count": 1, "min": 3, "max": 3}, "Number of Records Since Last Reset": {"sum": 20.0, "count": 1, "min": 20, "max": 20}, "Number of Batches Since Last Reset": {"sum": 5.0, "count": 1, "min": 5, "max": 5}}}
[03/15/2026 11:36:30 INFO 139913908160320] #throughput_metric: host=algo-1, train throughput=305.6994901733556 records/second

In [36]:
linear_regresor=linear.deploy(initial_instance_count=1,instance_type="ml.m4.xlarge")

INFO:sagemaker:Creating model with name: linear-learner-2026-03-15-11-38-32-040
INFO:sagemaker:Creating endpoint-config with name linear-learner-2026-03-15-11-38-32-040
INFO:sagemaker:Creating endpoint with name linear-learner-2026-03-15-11-38-32-040

-------!

In [40]:
linear_regresor.serializer = sagemaker.serializers.CSVSerializer()
linear_regresor.deserializer = sagemaker.deserializers.JSONDeserializer()

In [41]:
results=linear_regresor.predict(X_test)

In [42]:
results

{'predictions': [{'score': 86.19189453125},
  {'score': 41.73332977294922},
  {'score': 53.06590270996094},
  {'score': 75.73104858398438},
  {'score': 37.37464904785156}]}

In [46]:
predictions = np.array([i["score"] for i in results["predictions"]])

In [47]:
predictions

array([86.19189453, 41.73332977, 53.06590271, 75.73104858, 37.37464905])